services:
  autoscraper:
    build: .
    container_name: kbtu-attendance
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    shm_size: '1g'
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - .env
    volumes:
      - ./data:/app/data
